baseurl = "http://support.senboll.com:8888/help"
# baseurl = "https://jameszhangchina.github.io/"
languageCode = "zh-CN"
# languageCode = "en-US"
defaultContentLanguage = "en"

title = "枫叶帮助中心"
theme = "gohugoioTheme"
themesdir = "themes/"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false

enableGitInfo = true

[params]
  editURL = ""
  description = ""
  author = "James"
  showVisitedLinks = true
  ## Gh repo (include trailing slash)
  ghrepo = "https://github.com/JamesZhangChina/support.senboll.com.help/"

[[Languages.en.menu.shortcuts]] 
name = "系统拓扑图"
identifier = "ds"
url = "/paradox-frame/"
weight = 10