baseURL = "http://support.senboll.com:8888/docs"
languageCode = "zh-CN"
defaultContentLanguage = "en"

title = "枫叶文档中心"
theme = "gohugoioTheme"
themesdir = "themes/"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false

enableGitInfo = true

[params]
  editURL = ""
  description = ""
  author = "James"
  showVisitedLinks = true

[[Languages.en.menu.shortcuts]] 
name = "系统拓扑图"
identifier = "ds"
url = "/paradox-frame/"
weight = 10

[markup.goldmark.renderer]
unsafe= true