
# Chinese menus

[[docs]]
  name = "基础知识"
  weight = 1
  identifier = "基础知识"
  post = "break"
  url = "/node1/"

[[docs]]
  name = "安装调试"
  weight = 5
  identifier = "安装调试"
  post = "break"
  url = "/node2/"

[[docs]]
  name = "用户指南"
  weight = 10
  identifier = "用户指南"
  post = "break"
  url = "/node3/"

[[docs]]
  name = "常见问题"
  weight = 15
  identifier = "常见问题"
  post = "break"
  url = "/node4/"

[[docs]]
  name = "系统框架"
  weight = 20
  identifier = "paradox-frame"
  post = "break"
  url = "/paradox-frame/"

[[docs]]
  name = "其他"
  weight = 25
  identifier = "其他"
  post = "break"
  url = "/node9/"

# Core languages.zh.menus

# LOW LEVEL ITEMS


# [[global]]
#   name = "首页"
#   weight = 1
#   identifier = "home"
#   post = "break"
#   url = "https://www.senboll.com"

# [[global]]
#   name = "关于"
#   weight = 2
#   identifier = "about"
#   post = "break"
#   url = "https://www.senboll.com/zh-hans/about"

[[global]]
  name = "主页"
  weight = 1
  identifier = "docs"
  url = "/"

# Anything with a weight > 100 gets an external icon
[[global]]
  name = "资料服务器"
  weight = 150
  icon = true
  identifier = "file-server"
  post = "external"
  url = "http://support.senboll.com:8888/files"

[[global]]
  name = "案例相册"
  weight = 200
  identifier = "usage"
  post = "external"
  url = "http://support.senboll.com:8888/photos"

[[global]]
  name = "枫叶APP缴费"
  weight = 250
  identifier = "swan-pay"
  post = "external"
  url = "http://support.senboll.com:8888/swan"

