
# Chinese menus

[[docs]]
  name = "理论基础"
  weight = 1
  identifier = "理论基础"
  post = "break"
  url = "/node1/"

[[docs]]
  name = "安装和维护"
  weight = 5
  identifier = "安装和维护"
  post = "break"
  url = "/node2/"

[[docs]]
  name = "常见问题"
  weight = 15
  identifier = "常见问题"
  post = "break"
  url = "/node3/"

[[docs]]
  name = "其他"
  weight = 20
  identifier = "其他"
  post = "break"
  url = "/node9/"

# Core languages.zh.menus

# LOW LEVEL ITEMS


[[global]]
  name = "关于"
  weight = 1
  identifier = "about"
  post = "break"
  url = "/about/"

[[global]]
  name = "文档中心"
  weight = 2
  identifier = "docs"
  url = "/documentation/"

[[global]]
  name = "系统框架"
  weight = 3
  identifier = "paradox-frame"
  post = "external"
  url = "/paradox-frame/"

# Anything with a weight > 100 gets an external icon
[[global]]
  name = "资料服务器"
  weight = 150
  icon = true
  identifier = "file-server"
  post = "external"
  url = "http://support.senboll.com:8888"

[[global]]
  name = "案例相册"
  weight = 200
  identifier = "usage"
  post = "external"
  url = "http://support.senboll.com:8888/usage"
